### PR TITLE
Fix issues

### LINKED ISSUE #4: Not trolling but embarrassing
Sorry but your code is not trolling, but embarrassing. The code is horrible. fprintf can pad with ' ' (and even with generic padding character with a little push) and at least you should use memset and strcpy instead of the for loops.

### PR DESCRIPTION
**Pull request by lovenunu**
This PR aims to fix #4 and #5
Moreover, it fixes tests texts and Readme.

Hey @oerdnj, is it less embarrassing now ?

### CODE REVIEW

File: leftpad-test.c [hunk 1]
```diff
@@ -4,31 +4,28 @@
 
 #include "leftpad.h"
 
-int do_test(char* a, char *b)
+int do_test(char* a, char* b)
 {
     return 0 != strcmp(a, b);
```
Comment (oerdnj) [inline leftpad-test.c]: Wait, what? `#define do_test(a,b) !strcmp(a, b);`
